/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/Home/AboutUs.vue')['default']
    Box: typeof import('./src/components/Details/Box.vue')['default']
    Breadcrumb: typeof import('./src/components/Details/Breadcrumb.vue')['default']
    BreadCrumbs: typeof import('./src/components/Products/BreadCrumbs.vue')['default']
    Card: typeof import('./src/components/Products/Card.vue')['default']
    Carousel: typeof import('./src/components/Home/Carousel.vue')['default']
    Cart: typeof import('./src/components/Header/Cart.vue')['default']
    CartButton: typeof import('./src/components/Header/CartButton.vue')['default']
    Contact: typeof import('./src/views/Contact.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    DropDownFilters: typeof import('./src/components/Products/DropDownFilters.vue')['default']
    FilterBar: typeof import('./src/components/Products/FilterBar.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Grid: typeof import('./src/components/Products/Grid.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./src/components/Cart/Item.vue')['default']
    Logo: typeof import('./src/components/Header/Logo.vue')['default']
    MobileMenu: typeof import('./src/components/Header/MobileMenu.vue')['default']
    MoreButton: typeof import('./src/components/Products/MoreButton.vue')['default']
    NavLinks: typeof import('./src/components/Header/NavLinks.vue')['default']
    Newsletter: typeof import('./src/components/Newsletter.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Profile: typeof import('./src/components/Header/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Header/SearchBar.vue')['default']
    Text: typeof import('./src/components/Details/Text.vue')['default']
    Total: typeof import('./src/components/Cart/Total.vue')['default']
    UserModal: typeof import('./src/components/Header/UserModal.vue')['default']
  }
}
