/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    AboutUs: typeof import('./src/components/Home/AboutUs.vue')['default']
    Basket: typeof import('./src/components/Header/Basket.vue')['default']
    BasketButton: typeof import('./src/components/Header/BasketButton.vue')['default']
    Breadcrumb: typeof import('./src/components/PDP/Breadcrumb.vue')['default']
    BreadCrumbs: typeof import('./src/components/Products/BreadCrumbs.vue')['default']
    ButtonComponent: typeof import('./src/components/UI/ButtonComponent.vue')['default']
    Carousel: typeof import('./src/components/Home/Carousel.vue')['default']
    CategoryFilter: typeof import('./src/components/Filters/CategoryFilter.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    Item: typeof import('./src/components/Cart/Item.vue')['default']
    Logo: typeof import('./src/components/Header/Logo.vue')['default']
    MobileMenu: typeof import('./src/components/Header/MobileMenu.vue')['default']
    NavLinks: typeof import('./src/components/Header/NavLinks.vue')['default']
    Newsletter: typeof import('./src/components/Newsletter.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    PDPText: typeof import('./src/components/PDP/PDPText.vue')['default']
    PLP: typeof import('./src/components/Products/PLP.vue')['default']
    ProductTile: typeof import('./src/components/PDP/ProductTile.vue')['default']
    RelatedProducts: typeof import('./src/components/Products/RelatedProducts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Header/SearchBar.vue')['default']
    SidebarNavigation: typeof import('./src/components/Products/SidebarNavigation.vue')['default']
    SortingFilter: typeof import('./src/components/Filters/SortingFilter.vue')['default']
    Total: typeof import('./src/components/Cart/Total.vue')['default']
  }
}
